entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  ws4000:
    address: ":4000"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  leresolver:
    acme:
      email: it@iterum.lv
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare

api:
  dashboard: true

log:
  level: INFO  # Or DEBUG if troubleshooting
